services:
  nginx:
    image: nginx:latest
    ports:
      - "8083:80"
    volumes:
      - ./contenido_nginx:/usr/share/nginx/html:ro
    restart: unless-stopped

  apache:
    image: httpd:latest
    ports:
      - "8084:80"
    volumes:
      - ./contenido_apache:/usr/local/apache2/htdocs:ro
    restart: unless-stopped
